[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Redirects for clean embed URLs
[[redirects]]
  from = "/embed/tone-checker"
  to = "/?embed=true&tool=tone"
  status = 200

[[redirects]]
  from = "/embed/palindrome"
  to = "/?embed=true&tool=palindrome"  
  status = 200

[[redirects]]
  from = "/embed/rhyming"
  to = "/?embed=true&tool=rhyming"
  status = 200

[[redirects]]
  from = "/embed/essay-hooks"
  to = "/?embed=true&tool=essay-hook"
  status = 200

[[redirects]]
  from = "/embed/action-generator"
  to = "/?embed=true&tool=action-generator"
  status = 200

[[redirects]]
  from = "/embed/descriptive-generator"
  to = "/?embed=true&tool=descriptive-generator"
  status = 200

[[redirects]]
  from = "/embed/filler-words"
  to = "/?embed=true&tool=filler-words"
  status = 200

[[redirects]]
  from = "/embed/conjunction-tool"
  to = "/?embed=true&tool=conjunction-tool"
  status = 200

[[redirects]]
  from = "/embed/writing-software-quiz"
  to = "/?embed=true&tool=writing-software-quiz"
  status = 200

[[redirects]]
  from = "/embed/strong-female-character"
  to = "/?embed=true&tool=strong-female-character"
  status = 200

[[redirects]]
  from = "/embed/report-topics"
  to = "/?embed=true&tool=report-topics"
  status = 200

[[redirects]]
  from = "/embed/grammar-examples"
  to = "/?embed=true&tool=grammar-examples"
  status = 200

[[redirects]]
  from = "/embed/poetry-words"
  to = "/?embed=true&tool=poetry-words"
  status = 200

[[redirects]]
  from = "/embed/writing-quality-scorer"
  to = "/?embed=true&tool=writing-quality-scorer"
  status = 200

[[redirects]]
  from = "/embed/random-words"
  to = "/?embed=true&tool=random-words"
  status = 200

[[redirects]]
  from = "/embed/romantic-words"
  to = "/?embed=true&tool=romantic-words"
  status = 200

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for iframe embedding
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ALLOWALL"
    Content-Security-Policy = "frame-ancestors https://becomeawritertoday.com https://*.becomeawritertoday.com" 